[
  inputs: [
    "*.ex",
    "*.exs",
    "lib/spacecast/**/*.ex",
    "lib/spacecast/**/*.exs",
    "lib/spacecast_web/**/*.ex",
    "lib/spacecast_web/**/*.exs",
    "lib/spacecast_core/**/*.ex",
    "lib/spacecast_core/**/*.exs",
    "lib/events/**/*.ex",
    "lib/events/**/*.exs",
    "lib/mix/**/*.ex",
    "lib/mix/**/*.exs",
    "test/**/*.ex",
    "test/**/*.exs",
    "config/**/*.exs",
    "priv/**/*.ex",
    "priv/**/*.exs",
    "scripts/**/*.ex",
    "scripts/**/*.exs"
  ],
  subdirectories: [
    "lib",
    "test",
    "config",
    "priv",
    "scripts"
  ],
  line_length: 120,
  locals_without_parens: [
    # Phoenix LiveView
    action: 2,
    attr: 3,
    attr: 2,
    class: 1,
    class: 2,
    form: 2,
    form: 3,
    input: 2,
    input: 3,
    label: 2,
    label: 3,
    link: 2,
    link: 3,
    meta: 2,
    meta: 3,
    option: 2,
    option: 3,
    select: 2,
    select: 3,
    slot: 1,
    slot: 2,
    slot: 3,
    slot: 4,
    textarea: 2,
    textarea: 3,
    # Phoenix
    get: 3,
    get: 4,
    post: 3,
    post: 4,
    put: 3,
    put: 4,
    patch: 3,
    patch: 4,
    delete: 3,
    delete: 4,
    resources: 2,
    resources: 3,
    scope: 2,
    scope: 3,
    pipe_through: 1,
    forward: 2,
    forward: 3,
    plug: 1,
    plug: 2,
    # Ecto
    field: 2,
    field: 3,
    belongs_to: 2,
    belongs_to: 3,
    has_one: 2,
    has_one: 3,
    has_many: 2,
    has_many: 3,
    many_to_many: 2,
    many_to_many: 3,
    embeds_one: 2,
    embeds_one: 3,
    embeds_many: 2,
    embeds_many: 3,
    add: 2,
    add: 3,
    modify: 3,
    modify: 4,
    remove: 2,
    remove: 3,
    rename: 3,
    rename: 4,
    create: 1,
    create: 2,
    drop: 1,
    drop: 2,
    alter: 2,
    alter: 3,
    index: 2,
    index: 3,
    create_if_not_exists: 2,
    create_if_not_exists: 3,
    drop_if_exists: 2,
    drop_if_exists: 3,
    # ExUnit
    test: 2,
    test: 3,
    describe: 2,
    describe: 3,
    setup: 1,
    setup: 2,
    setup: 3,
    setup_all: 1,
    setup_all: 2,
    setup_all: 3,
    on_exit: 1,
    on_exit: 2,
    # Credo
    check: 1,
    check: 2,
    # Mix
    defproject: 2,
    defapplication: 2,
    deps: 1,
    deps: 2,
    aliases: 1,
    aliases: 2,
    compilers: 1,
    compilers: 2,
    elixirc_paths: 1,
    elixirc_paths: 2,
    # Common patterns
    def: 1,
    def: 2,
    defp: 1,
    defp: 2,
    defmodule: 2,
    defprotocol: 2,
    defimpl: 2,
    defimpl: 3,
    defstruct: 1,
    defstruct: 2,
    defexception: 1,
    defexception: 2,
    defcallback: 1,
    defcallback: 2,
    defmacrocallback: 1,
    defmacrocallback: 2,
    defoverridable: 1,
    defoverridable: 2,
    defguard: 1,
    defguard: 2,
    defguardp: 1,
    defguardp: 2,
    defmacro: 1,
    defmacro: 2,
    defmacrop: 1,
    defmacrop: 2,
    defdelegate: 2,
    defdelegate: 3,
    defconfig: 2,
    defconfig: 3,
    defconfigp: 2,
    defconfigp: 3,
    # Common function calls
    assert: 1,
    assert: 2,
    assert_in_delta: 3,
    assert_in_delta: 4,
    assert_raise: 1,
    assert_raise: 2,
    assert_raise: 3,
    assert_receive: 1,
    assert_receive: 2,
    assert_receive: 3,
    assert_send: 1,
    assert_send: 2,
    assert_send: 3,
    refute: 1,
    refute: 2,
    refute_receive: 1,
    refute_receive: 2,
    refute_receive: 3,
    refute_send: 1,
    refute_send: 2,
    refute_send: 3,
    # Logger
    debug: 1,
    debug: 2,
    info: 1,
    info: 2,
    warn: 1,
    warn: 2,
    error: 1,
    error: 2,
    # Common patterns
    if: 2,
    if: 3,
    unless: 2,
    unless: 3,
    case: 2,
    case: 3,
    cond: 1,
    with: 1,
    with: 2,
    for: 1,
    for: 2,
    import: 1,
    import: 2,
    import: 3,
    require: 1,
    require: 2,
    alias: 1,
    alias: 2,
    alias: 3,
    use: 1,
    use: 2,
    quote: 1,
    quote: 2,
    unquote: 1,
    unquote: 2,
    unquote_splicing: 1,
    unquote_splicing: 2,
    # Common macros
    sigil_S: 2,
    sigil_s: 2,
    sigil_W: 2,
    sigil_w: 2,
    sigil_C: 2,
    sigil_c: 2,
    sigil_R: 2,
    sigil_r: 2,
    sigil_T: 2,
    sigil_t: 2,
    sigil_D: 2,
    sigil_d: 2,
    sigil_U: 2,
    sigil_u: 2,
    sigil_H: 2,
    sigil_h: 2,
    sigil_N: 2,
    sigil_n: 2,
    sigil_A: 2,
    sigil_a: 2,
    sigil_K: 2,
    sigil_k: 2,
    sigil_P: 2,
    sigil_p: 2,
    sigil_B: 2,
    sigil_b: 2,
    sigil_F: 2,
    sigil_f: 2,
    sigil_E: 2,
    sigil_e: 2,
    sigil_I: 2,
    sigil_i: 2,
    sigil_L: 2,
    sigil_l: 2,
    sigil_M: 2,
    sigil_m: 2,
    sigil_O: 2,
    sigil_o: 2,
    sigil_V: 2,
    sigil_v: 2,
    sigil_X: 2,
    sigil_x: 2,
    sigil_Y: 2,
    sigil_y: 2,
    sigil_Z: 2,
    sigil_z: 2
  ],
  export: [
    locals_without_parens: [
      # Add any project-specific locals here
    ]
  ]
]
