{application,libsignal_protocol_nif,
             [{description,"Signal Protocol cryptographic primitives NIF implementation"},
              {vsn,"0.1.1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[libsignal_protocol_nif,libsignal_protocol_nif_v2,
                        signal_nif]},
              {licenses,["Apache-2.0"]},
              {links,[{"GitHub",
                       "https://github.com/Hydepwns/libsignal-protocol-nif"}]}]}.
