FROM elixir:1.14.3

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    inotify-tools \
    postgresql-client \
    nodejs \
    npm \
    git \
    && apt-get clean \
    && rm -f /var/lib/apt/lists/*_*

# Create app directory and copy the Elixir projects into it
WORKDIR /app

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force && \
    mix archive.install hex phx_new 1.7.0 --force

# Copy configuration files
COPY config ./config
COPY mix.exs mix.lock ./

# Get dependencies
RUN mix deps.get

# Copy assets
COPY assets ./priv/static/assets
RUN cd priv/static/assets && npm install

# Copy remaining application code
COPY . .

# Run the Phoenix server
CMD ["mix", "phx.server"] 