version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: spacecast_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - elixir_deps:/app/deps
      - build_cache:/app/_build
      - node_modules:/app/assets/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/spacecast_dev
      - MIX_ENV=dev
      - PORT=4000
    command: mix phx.server

  db:
    image: postgres:13
    container_name: spacecast_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spacecast_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=150'

  test_db:
    image: postgres:13
    container_name: spacecast_test_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spacecast_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: postgres -c 'max_connections=150'

volumes:
  postgres_data:
  postgres_test_data:
  elixir_deps:
  build_cache:
  node_modules:
